services:
  postgres:
    container_name: postgres-sql-employeemanager
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15102003
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: employeemanager
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - login-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-employeemanager
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  login-demo:
    driver: bridge

volumes:
  postgres:
    driver: local