version: '3.8'
services:
  postgres:
    container_name: postgres-sql-employeemanager
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15102003
      POSTGRES_DB: employeemanager
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - employeemanager
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-employeemanager
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - employeemanager

networks:
  employeemanager:
    driver: bridge

volumes:
  postgres:
    driver: local
